// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package com.lawsofnature.apigateway.domain.http.req

object ReqProto {
  lazy val descriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val proto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(
      com.trueaccord.scalapb.Encoding.fromBase64(scala.collection.Seq(
  """CglyZXEucHJvdG8isgEKHFNlbmRMb2dpblZlcmlmaWNhdGlvbkNvZGVSZXESHgoKZGV2aWNlVHlwZRgBIAEoBVIKZGV2aWNlV
  HlwZRIgCgtmaW5nZXJQcmludBgCIAEoCVILZmluZ2VyUHJpbnQSFgoGbW9iaWxlGAMgASgJUgZtb2JpbGUSFgoGcmVzZW5kGAQgA
  SgIUgZyZXNlbmQSIAoLbGFzdENoYW5uZWwYBSABKAVSC2xhc3RDaGFubmVsIqwBCghMb2dpblJlcRIaCghjbGllbnRJZBgBIAEoB
  VIIY2xpZW50SWQSHgoKZGV2aWNlVHlwZRgCIAEoBVIKZGV2aWNlVHlwZRIgCgtmaW5nZXJQcmludBgDIAEoCVILZmluZ2VyUHJpb
  nQSFgoGbW9iaWxlGAQgASgJUgZtb2JpbGUSKgoQdmVyaWZpY2F0aW9uQ29kZRgFIAEoCVIQdmVyaWZpY2F0aW9uQ29kZSKCAQoMQ
  XV0b0xvZ2luUmVxEhoKCGNsaWVudElkGAEgASgFUghjbGllbnRJZBIeCgpkZXZpY2VUeXBlGAIgASgFUgpkZXZpY2VUeXBlEiAKC
  2ZpbmdlclByaW50GAMgASgJUgtmaW5nZXJQcmludBIUCgV0b2tlbhgEIAEoCVIFdG9rZW5CKQonY29tLmxhd3NvZm5hdHVyZS5hc
  GlnYXRld2F5LmRvbWFpbi5odHRwYgZwcm90bzM="""
      ).mkString))
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(proto, Array(
    ))
  }
}