// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package com.lawsofnature.apigateway.domain.http.req

object ReqProto {
  lazy val descriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val proto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(
      com.trueaccord.scalapb.Encoding.fromBase64(scala.collection.Seq(
        """CglyZXEucHJvdG8ilgIKHFNlbmRMb2dpblZlcmlmaWNhdGlvbkNvZGVSZXESHgoKZGV2aWNlVHlwZRgBIAEoBVIKZGV2aWNlV
  HlwZRIgCgtmaW5nZXJQcmludBgCIAEoCVILZmluZ2VyUHJpbnQSFgoGbW9iaWxlGAMgASgJUgZtb2JpbGUSFgoGcmVzZW5kGAQgA
  SgIUgZyZXNlbmQSIAoLbGFzdENoYW5uZWwYBSABKAVSC2xhc3RDaGFubmVsEhIKBGV4dDEYBiABKAlSBGV4dDESEgoEZXh0MhgHI
  AEoCVIEZXh0MhISCgRleHQzGAggASgJUgRleHQzEhIKBGV4dDQYCSABKAlSBGV4dDQSEgoEZXh0NRgKIAEoCVIEZXh0NSKQAgoIT
  G9naW5SZXESGgoIY2xpZW50SWQYASABKAVSCGNsaWVudElkEh4KCmRldmljZVR5cGUYAiABKAVSCmRldmljZVR5cGUSIAoLZmluZ
  2VyUHJpbnQYAyABKAlSC2ZpbmdlclByaW50EhYKBm1vYmlsZRgEIAEoCVIGbW9iaWxlEioKEHZlcmlmaWNhdGlvbkNvZGUYBSABK
  AlSEHZlcmlmaWNhdGlvbkNvZGUSEgoEZXh0MRgGIAEoCVIEZXh0MRISCgRleHQyGAcgASgJUgRleHQyEhIKBGV4dDMYCCABKAlSB
  GV4dDMSEgoEZXh0NBgJIAEoCVIEZXh0NBISCgRleHQ1GAogASgJUgRleHQ1IukBCg9Mb2dpbkJ5VG9rZW5SZXESGgoIY2xpZW50S
  WQYASABKAVSCGNsaWVudElkEh4KCmRldmljZVR5cGUYAiABKAVSCmRldmljZVR5cGUSIAoLZmluZ2VyUHJpbnQYAyABKAlSC2Zpb
  mdlclByaW50EhQKBXRva2VuGAQgASgJUgV0b2tlbhISCgRleHQxGAUgASgJUgRleHQxEhIKBGV4dDIYBiABKAlSBGV4dDISEgoEZ
  Xh0MxgHIAEoCVIEZXh0MxISCgRleHQ0GAggASgJUgRleHQ0EhIKBGV4dDUYCSABKAlSBGV4dDVCKQonY29tLmxhd3NvZm5hdHVyZ
  S5hcGlnYXRld2F5LmRvbWFpbi5odHRwYgZwcm90bzM="""
      ).mkString))
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(proto, Array(
    ))
  }
}