// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package com.lawsofnature.apigateway.domain.http.req

object ReqProto {
  lazy val descriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val proto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(
      com.trueaccord.scalapb.Encoding.fromBase64(scala.collection.Seq(
  """CglyZXEucHJvdG8isgEKHFNlbmRMb2dpblZlcmlmaWNhdGlvbkNvZGVSZXESHgoKZGV2aWNlVHlwZRgBIAEoBVIKZGV2aWNlV
  HlwZRIgCgtmaW5nZXJQcmludBgCIAEoCVILZmluZ2VyUHJpbnQSFgoGbW9iaWxlGAMgASgJUgZtb2JpbGUSFgoGcmVzZW5kGAQgA
  SgIUgZyZXNlbmQSIAoLbGFzdENoYW5uZWwYBSABKAVSC2xhc3RDaGFubmVsIpABCghMb2dpblJlcRIeCgpkZXZpY2VUeXBlGAEgA
  SgFUgpkZXZpY2VUeXBlEiAKC2ZpbmdlclByaW50GAIgASgJUgtmaW5nZXJQcmludBIWCgZtb2JpbGUYAyABKAlSBm1vYmlsZRIqC
  hB2ZXJpZmljYXRpb25Db2RlGAQgASgJUhB2ZXJpZmljYXRpb25Db2RlImYKDEF1dG9Mb2dpblJlcRIeCgpkZXZpY2VUeXBlGAEgA
  SgFUgpkZXZpY2VUeXBlEiAKC2ZpbmdlclByaW50GAIgASgJUgtmaW5nZXJQcmludBIUCgV0b2tlbhgDIAEoCVIFdG9rZW5CKQonY
  29tLmxhd3NvZm5hdHVyZS5hcGlnYXRld2F5LmRvbWFpbi5odHRwYgZwcm90bzM="""
      ).mkString))
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(proto, Array(
    ))
  }
}