// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package com.lawsofnature.apigateway.domain.http.req

import com.lawsofnature.apigateway.validate.Validator.Validate
import com.lawsofnature.common.exception.ErrorCode._

@SerialVersionUID(0L)
final case class SendLoginVerificationCodeReq(
                                               @Validate(required = true, min = 1, max = 4, error = EC_INVALID_REQUEST)
                                               deviceType: Int = 0,
                                               @Validate(required = true, maxLength = 128, error = EC_INVALID_REQUEST)
                                               fingerPrint: String = "",
                                               @Validate(required = true, mask = "^[1]([3][0-9]{1}|([4][7]{1})|([5][0-3|5-9]{1})|([8][0-9]{1}))[0-9]{8}$", error = EC_UC_INVALID_MOBILE)
                                               mobile: String = "",
                                               resend: Boolean = false,
                                               lastChannel: Int = 0
                                             ) extends com.trueaccord.scalapb.GeneratedMessage with com.trueaccord.scalapb.Message[SendLoginVerificationCodeReq] with com.trueaccord.lenses.Updatable[SendLoginVerificationCodeReq] {
  @transient
  private[this] var __serializedSizeCachedValue: Int = 0

  private[this] def __computeSerializedValue(): Int = {
    var __size = 0
    if (deviceType != 0) {
      __size += _root_.com.google.protobuf.CodedOutputStream.computeInt32Size(1, deviceType)
    }
    if (fingerPrint != "") {
      __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(2, fingerPrint)
    }
    if (mobile != "") {
      __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(3, mobile)
    }
    if (resend != false) {
      __size += _root_.com.google.protobuf.CodedOutputStream.computeBoolSize(4, resend)
    }
    if (lastChannel != 0) {
      __size += _root_.com.google.protobuf.CodedOutputStream.computeInt32Size(5, lastChannel)
    }
    __size
  }

  final override def serializedSize: Int = {
    var read = __serializedSizeCachedValue
    if (read == 0) {
      read = __computeSerializedValue()
      __serializedSizeCachedValue = read
    }
    read
  }

  def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): Unit = {
    {
      val __v = deviceType
      if (__v != 0) {
        _output__.writeInt32(1, __v)
      }
    };
    {
      val __v = fingerPrint
      if (__v != "") {
        _output__.writeString(2, __v)
      }
    };
    {
      val __v = mobile
      if (__v != "") {
        _output__.writeString(3, __v)
      }
    };
    {
      val __v = resend
      if (__v != false) {
        _output__.writeBool(4, __v)
      }
    };
    {
      val __v = lastChannel
      if (__v != 0) {
        _output__.writeInt32(5, __v)
      }
    };
  }

  def mergeFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): com.lawsofnature.apigateway.domain.http.req.SendLoginVerificationCodeReq = {
    var __deviceType = this.deviceType
    var __fingerPrint = this.fingerPrint
    var __mobile = this.mobile
    var __resend = this.resend
    var __lastChannel = this.lastChannel
    var _done__ = false
    while (!_done__) {
      val _tag__ = _input__.readTag()
      _tag__ match {
        case 0 => _done__ = true
        case 8 =>
          __deviceType = _input__.readInt32()
        case 18 =>
          __fingerPrint = _input__.readString()
        case 26 =>
          __mobile = _input__.readString()
        case 32 =>
          __resend = _input__.readBool()
        case 40 =>
          __lastChannel = _input__.readInt32()
        case tag => _input__.skipField(tag)
      }
    }
    com.lawsofnature.apigateway.domain.http.req.SendLoginVerificationCodeReq(
      deviceType = __deviceType,
      fingerPrint = __fingerPrint,
      mobile = __mobile,
      resend = __resend,
      lastChannel = __lastChannel
    )
  }

  def withDeviceType(__v: Int): SendLoginVerificationCodeReq = copy(deviceType = __v)

  def withFingerPrint(__v: String): SendLoginVerificationCodeReq = copy(fingerPrint = __v)

  def withMobile(__v: String): SendLoginVerificationCodeReq = copy(mobile = __v)

  def withResend(__v: Boolean): SendLoginVerificationCodeReq = copy(resend = __v)

  def withLastChannel(__v: Int): SendLoginVerificationCodeReq = copy(lastChannel = __v)

  def getField(__field: _root_.com.google.protobuf.Descriptors.FieldDescriptor): scala.Any = {
    __field.getNumber match {
      case 1 => {
        val __t = deviceType
        if (__t != 0) __t else null
      }
      case 2 => {
        val __t = fingerPrint
        if (__t != "") __t else null
      }
      case 3 => {
        val __t = mobile
        if (__t != "") __t else null
      }
      case 4 => {
        val __t = resend
        if (__t != false) __t else null
      }
      case 5 => {
        val __t = lastChannel
        if (__t != 0) __t else null
      }
    }
  }

  override def toString: String = _root_.com.trueaccord.scalapb.TextFormat.printToUnicodeString(this)

  def companion = com.lawsofnature.apigateway.domain.http.req.SendLoginVerificationCodeReq
}

object SendLoginVerificationCodeReq extends com.trueaccord.scalapb.GeneratedMessageCompanion[com.lawsofnature.apigateway.domain.http.req.SendLoginVerificationCodeReq] {
  implicit def messageCompanion: com.trueaccord.scalapb.GeneratedMessageCompanion[com.lawsofnature.apigateway.domain.http.req.SendLoginVerificationCodeReq] = this

  def fromFieldsMap(__fieldsMap: scala.collection.immutable.Map[_root_.com.google.protobuf.Descriptors.FieldDescriptor, scala.Any]): com.lawsofnature.apigateway.domain.http.req.SendLoginVerificationCodeReq = {
    require(__fieldsMap.keys.forall(_.getContainingType() == descriptor), "FieldDescriptor does not match message type.")
    val __fields = descriptor.getFields
    com.lawsofnature.apigateway.domain.http.req.SendLoginVerificationCodeReq(
      __fieldsMap.getOrElse(__fields.get(0), 0).asInstanceOf[Int],
      __fieldsMap.getOrElse(__fields.get(1), "").asInstanceOf[String],
      __fieldsMap.getOrElse(__fields.get(2), "").asInstanceOf[String],
      __fieldsMap.getOrElse(__fields.get(3), false).asInstanceOf[Boolean],
      __fieldsMap.getOrElse(__fields.get(4), 0).asInstanceOf[Int]
    )
  }

  def descriptor: _root_.com.google.protobuf.Descriptors.Descriptor = ReqProto.descriptor.getMessageTypes.get(0)

  def messageCompanionForField(__field: _root_.com.google.protobuf.Descriptors.FieldDescriptor): _root_.com.trueaccord.scalapb.GeneratedMessageCompanion[_] = throw new MatchError(__field)

  def enumCompanionForField(__field: _root_.com.google.protobuf.Descriptors.FieldDescriptor): _root_.com.trueaccord.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__field)

  lazy val defaultInstance = com.lawsofnature.apigateway.domain.http.req.SendLoginVerificationCodeReq(
  )

  implicit class SendLoginVerificationCodeReqLens[UpperPB](_l: _root_.com.trueaccord.lenses.Lens[UpperPB, com.lawsofnature.apigateway.domain.http.req.SendLoginVerificationCodeReq]) extends _root_.com.trueaccord.lenses.ObjectLens[UpperPB, com.lawsofnature.apigateway.domain.http.req.SendLoginVerificationCodeReq](_l) {
    def deviceType: _root_.com.trueaccord.lenses.Lens[UpperPB, Int] = field(_.deviceType)((c_, f_) => c_.copy(deviceType = f_))

    def fingerPrint: _root_.com.trueaccord.lenses.Lens[UpperPB, String] = field(_.fingerPrint)((c_, f_) => c_.copy(fingerPrint = f_))

    def mobile: _root_.com.trueaccord.lenses.Lens[UpperPB, String] = field(_.mobile)((c_, f_) => c_.copy(mobile = f_))

    def resend: _root_.com.trueaccord.lenses.Lens[UpperPB, Boolean] = field(_.resend)((c_, f_) => c_.copy(resend = f_))

    def lastChannel: _root_.com.trueaccord.lenses.Lens[UpperPB, Int] = field(_.lastChannel)((c_, f_) => c_.copy(lastChannel = f_))
  }

  final val DEVICETYPE_FIELD_NUMBER = 1
  final val FINGERPRINT_FIELD_NUMBER = 2
  final val MOBILE_FIELD_NUMBER = 3
  final val RESEND_FIELD_NUMBER = 4
  final val LASTCHANNEL_FIELD_NUMBER = 5
}
