// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package com.lawsofnature.apigateway.domain.http.resp

object RespProto {
  lazy val descriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val proto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(
      com.trueaccord.scalapb.Encoding.fromBase64(scala.collection.Seq(
  """CgpyZXNwLnByb3RvIl8KHVNlbmRMb2dpblZlcmlmaWNhdGlvbkNvZGVSZXNwEhIKBGNvZGUYASABKAlSBGNvZGUSEAoDbXNnG
  AIgASgJUgNtc2cSGAoHY2hhbm5lbBgDIAEoBVIHY2hhbm5lbCJxCglMb2dpblJlc3ASEgoEY29kZRgBIAEoCVIEY29kZRIQCgNtc
  2cYAiABKAlSA21zZxIUCgV0b2tlbhgDIAEoCVIFdG9rZW4SEAoDa2V5GAQgASgJUgNrZXkSFgoGbW9iaWxlGAUgASgJUgZtb2Jpb
  GVCKQonY29tLmxhd3NvZm5hdHVyZS5hcGlnYXRld2F5LmRvbWFpbi5odHRwYgZwcm90bzM="""
      ).mkString))
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(proto, Array(
    ))
  }
}