// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package com.lawsofnature.apigateway.domain.http.resp

object RespProto {
  lazy val descriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val proto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(
      com.trueaccord.scalapb.Encoding.fromBase64(scala.collection.Seq(
  """CgpyZXNwLnByb3RvIjkKEVNpbXBsZUFwaVJlc3BvbnNlEhIKBGNvZGUYASABKAlSBGNvZGUSEAoDbXNnGAIgASgJUgNtc2ciX
  wodU2VuZExvZ2luVmVyaWZpY2F0aW9uQ29kZVJlc3ASEgoEY29kZRgBIAEoCVIEY29kZRIQCgNtc2cYAiABKAlSA21zZxIYCgdja
  GFubmVsGAMgASgFUgdjaGFubmVsInEKCUxvZ2luUmVzcBISCgRjb2RlGAEgASgJUgRjb2RlEhAKA21zZxgCIAEoCVIDbXNnEhQKB
  XRva2VuGAMgASgJUgV0b2tlbhIQCgNrZXkYBCABKAlSA2tleRIWCgZtb2JpbGUYBSABKAlSBm1vYmlsZUIpCidjb20ubGF3c29mb
  mF0dXJlLmFwaWdhdGV3YXkuZG9tYWluLmh0dHBiBnByb3RvMw=="""
      ).mkString))
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(proto, Array(
    ))
  }
}