// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package com.lawsofnature.apigateway.domain.http.resp

object RespProto {
  lazy val descriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val proto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(
      com.trueaccord.scalapb.Encoding.fromBase64(scala.collection.Seq(
  """CgpyZXNwLnByb3RvIosBChFTaW1wbGVBcGlSZXNwb25zZRISCgRjb2RlGAEgASgJUgRjb2RlEhIKBGV4dDEYAiABKAlSBGV4d
  DESEgoEZXh0MhgDIAEoCVIEZXh0MhISCgRleHQzGAQgASgJUgRleHQzEhIKBGV4dDQYBSABKAlSBGV4dDQSEgoEZXh0NRgGIAEoC
  VIEZXh0NSKxAQodU2VuZExvZ2luVmVyaWZpY2F0aW9uQ29kZVJlc3ASEgoEY29kZRgBIAEoCVIEY29kZRIYCgdjaGFubmVsGAIgA
  SgFUgdjaGFubmVsEhIKBGV4dDEYAyABKAlSBGV4dDESEgoEZXh0MhgEIAEoCVIEZXh0MhISCgRleHQzGAUgASgJUgRleHQzEhIKB
  GV4dDQYBiABKAlSBGV4dDQSEgoEZXh0NRgHIAEoCVIEZXh0NSLNAQoJTG9naW5SZXNwEhIKBGNvZGUYASABKAlSBGNvZGUSFAoFd
  G9rZW4YAiABKAlSBXRva2VuEhYKBm1vYmlsZRgDIAEoCVIGbW9iaWxlEhoKCG5pY2tOYW1lGAQgASgJUghuaWNrTmFtZRISCgRle
  HQxGAUgASgJUgRleHQxEhIKBGV4dDIYBiABKAlSBGV4dDISEgoEZXh0MxgHIAEoCVIEZXh0MxISCgRleHQ0GAggASgJUgRleHQ0E
  hIKBGV4dDUYCSABKAlSBGV4dDVCKQonY29tLmxhd3NvZm5hdHVyZS5hcGlnYXRld2F5LmRvbWFpbi5odHRwYgZwcm90bzM="""
      ).mkString))
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(proto, Array(
    ))
  }
}