// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package com.lawsofnature.apigateway.domain.http.req.pullresource

object PullresourceProto {
  lazy val descriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val proto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(
      com.trueaccord.scalapb.Encoding.fromBase64(scala.collection.Seq(
  """ChZyZXEvcHVsbHJlc291cmNlLnByb3RvIqEBCg9QdWxsUmVzb3VyY2VSZXESGAoHdmVyc2lvbhgBIAEoBVIHdmVyc2lvbhIQC
  gNsYW4YAiABKAlSA2xhbhISCgRleHQxGAMgASgJUgRleHQxEhIKBGV4dDIYBCABKAlSBGV4dDISEgoEZXh0MxgFIAEoCVIEZXh0M
  xISCgRleHQ0GAYgASgJUgRleHQ0EhIKBGV4dDUYByABKAlSBGV4dDVCLQorY29tLmxhd3NvZm5hdHVyZS5hcGlnYXRld2F5LmRvb
  WFpbi5odHRwLnJlcWIGcHJvdG8z"""
      ).mkString))
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(proto, Array(
    ))
  }
}