// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package com.jxjxgo.apigateway.domain.http.req.loginbytoken

object LoginbytokenProto {
  lazy val descriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val proto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(
      com.trueaccord.scalapb.Encoding.fromBase64(scala.collection.Seq(
        """ChZyZXEvbG9naW5ieXRva2VuLnByb3RvIoMCCg9Mb2dpbkJ5VG9rZW5SZXESGgoIY2xpZW50SWQYASABKAVSCGNsaWVudElkE
  hgKB3ZlcnNpb24YAiABKAlSB3ZlcnNpb24SHgoKZGV2aWNlVHlwZRgDIAEoBVIKZGV2aWNlVHlwZRIgCgtmaW5nZXJQcmludBgEI
  AEoCVILZmluZ2VyUHJpbnQSFAoFdG9rZW4YBSABKAlSBXRva2VuEhIKBGV4dDEYBiABKAlSBGV4dDESEgoEZXh0MhgHIAEoCVIEZ
  Xh0MhISCgRleHQzGAggASgJUgRleHQzEhIKBGV4dDQYCSABKAlSBGV4dDQSEgoEZXh0NRgKIAEoCVIEZXh0NUItCitjb20ubGF3c
  29mbmF0dXJlLmFwaWdhdGV3YXkuZG9tYWluLmh0dHAucmVxYgZwcm90bzM="""
      ).mkString))
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(proto, Array(
    ))
  }
}