// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package com.lawsofnature.apigateway.domain.http.resp.depositrequestresp

object DepositrequestrespProto {
  lazy val descriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val proto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(
      com.trueaccord.scalapb.Encoding.fromBase64(scala.collection.Seq(
  """Ch1yZXNwL2RlcG9zaXRyZXF1ZXN0cmVzcC5wcm90byLyAQoSRGVwb3NpdFJlcXVlc3RSZXNwEhIKBGNvZGUYASABKAlSBGNvZ
  GUSKgoQcGF5bWVudFZvdWNoZXJObxgCIAEoCVIQcGF5bWVudFZvdWNoZXJObxIgCgt0cmFkZVN0YXR1cxgDIAEoBVILdHJhZGVTd
  GF0dXMSFgoGZXh0VXJsGAQgASgJUgZleHRVcmwSEgoEZXh0MRgFIAEoCVIEZXh0MRISCgRleHQyGAYgASgJUgRleHQyEhIKBGV4d
  DMYByABKAlSBGV4dDMSEgoEZXh0NBgIIAEoCVIEZXh0NBISCgRleHQ1GAkgASgJUgRleHQ1Qi4KLGNvbS5sYXdzb2ZuYXR1cmUuY
  XBpZ2F0ZXdheS5kb21haW4uaHR0cC5yZXNwYgZwcm90bzM="""
      ).mkString))
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(proto, Array(
    ))
  }
}