// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package com.jxjxgo.apigateway.domain.http.req.depositrequest

object DepositrequestProto {
  lazy val descriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val proto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(
      com.trueaccord.scalapb.Encoding.fromBase64(scala.collection.Seq(
        """ChhyZXEvZGVwb3NpdHJlcXVlc3QucHJvdG8i8AEKDkRlcG9zaXRSZXF1ZXN0EiAKC2NoYW5uZWxDb2RlGAEgASgJUgtjaGFub
  mVsQ29kZRIcCglwcmljZUNvZGUYAiABKAlSCXByaWNlQ29kZRIUCgVwcmljZRgDIAEoCVIFcHJpY2USJAoNZGlhbW9uZEFtb3Vud
  BgEIAEoBVINZGlhbW9uZEFtb3VudBISCgRleHQxGAUgASgJUgRleHQxEhIKBGV4dDIYBiABKAlSBGV4dDISEgoEZXh0MxgHIAEoC
  VIEZXh0MxISCgRleHQ0GAggASgJUgRleHQ0EhIKBGV4dDUYCSABKAlSBGV4dDVCLQorY29tLmxhd3NvZm5hdHVyZS5hcGlnYXRld
  2F5LmRvbWFpbi5odHRwLnJlcWIGcHJvdG8z"""
      ).mkString))
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(proto, Array(
    ))
  }
}