// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package com.jxjxgo.apigateway.domain.http.req.sendcode

object SendcodeProto {
  lazy val descriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val proto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(
      com.trueaccord.scalapb.Encoding.fromBase64(scala.collection.Seq(
        """ChJyZXEvc2VuZGNvZGUucHJvdG8ilgIKHFNlbmRMb2dpblZlcmlmaWNhdGlvbkNvZGVSZXESHgoKZGV2aWNlVHlwZRgBIAEoB
  VIKZGV2aWNlVHlwZRIgCgtmaW5nZXJQcmludBgCIAEoCVILZmluZ2VyUHJpbnQSFgoGbW9iaWxlGAMgASgJUgZtb2JpbGUSFgoGc
  mVzZW5kGAQgASgJUgZyZXNlbmQSIAoLbGFzdENoYW5uZWwYBSABKAVSC2xhc3RDaGFubmVsEhIKBGV4dDEYBiABKAlSBGV4dDESE
  goEZXh0MhgHIAEoCVIEZXh0MhISCgRleHQzGAggASgJUgRleHQzEhIKBGV4dDQYCSABKAlSBGV4dDQSEgoEZXh0NRgKIAEoCVIEZ
  Xh0NUInCiVjb20uanhqeGdvLmFwaWdhdGV3YXkuZG9tYWluLmh0dHAucmVxYgZwcm90bzM="""
      ).mkString))
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(proto, Array(
    ))
  }
}