// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package com.jxjxgo.apigateway.domain.http.resp.checkgamestatus

object CheckgamestatusProto {
  lazy val descriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val proto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(
      com.trueaccord.scalapb.Encoding.fromBase64(scala.collection.Seq(
  """ChpyZXNwL2NoZWNrZ2FtZXN0YXR1cy5wcm90byLHAQoTQ2hlY2tHYW1lU3RhdHVzUmVzcBISCgRjb2RlGAEgASgJUgRjb2RlE
  hoKCG1lbWJlcklkGAIgASgDUghtZW1iZXJJZBIcCglyZWNvbm5lY3QYAyABKAhSCXJlY29ubmVjdBISCgRleHQxGAQgASgJUgRle
  HQxEhIKBGV4dDIYBSABKAlSBGV4dDISEgoEZXh0MxgGIAEoCVIEZXh0MxISCgRleHQ0GAcgASgJUgRleHQ0EhIKBGV4dDUYCCABK
  AlSBGV4dDVCKAomY29tLmp4anhnby5hcGlnYXRld2F5LmRvbWFpbi5odHRwLnJlc3BiBnByb3RvMw=="""
      ).mkString))
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(proto, Array(
    ))
  }
}