// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package com.lawsofnature.apigateway.domain.http.req.simple

object SimpleProto {
  lazy val descriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val proto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(
      com.trueaccord.scalapb.Encoding.fromBase64(scala.collection.Seq(
  """ChByZXEvc2ltcGxlLnByb3RvIp8BCglTaW1wbGVSZXESFgoGcGFyYW0wGAEgASgJUgZwYXJhbTASFgoGcGFyYW0xGAIgASgJU
  gZwYXJhbTESEgoEZXh0MRgDIAEoCVIEZXh0MRISCgRleHQyGAQgASgJUgRleHQyEhIKBGV4dDMYBSABKAlSBGV4dDMSEgoEZXh0N
  BgGIAEoCVIEZXh0NBISCgRleHQ1GAcgASgJUgRleHQ1Qi0KK2NvbS5sYXdzb2ZuYXR1cmUuYXBpZ2F0ZXdheS5kb21haW4uaHR0c
  C5yZXFiBnByb3RvMw=="""
      ).mkString))
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(proto, Array(
    ))
  }
}