// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package com.jxjxgo.apigateway.domain.http.resp.depositrecordresp

object DepositrecordrespProto {
  lazy val descriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val proto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(
      com.trueaccord.scalapb.Encoding.fromBase64(scala.collection.Seq(
        """ChxyZXNwL2RlcG9zaXRyZWNvcmRyZXNwLnByb3RvIqsDChFEZXBvc2l0UmVjb3JkUmVzcBISCgRjb2RlGAEgASgJUgRjb2RlE
  ioKEHBheW1lbnRWb3VjaGVyTm8YAiABKAlSEHBheW1lbnRWb3VjaGVyTm8SHAoJYWNjb3VudElkGAMgASgDUglhY2NvdW50SWQSG
  goIbWVtYmVySWQYBCABKANSCG1lbWJlcklkEhwKCXRyYWRlVHlwZRgFIAEoBVIJdHJhZGVUeXBlEiAKC3RyYWRlU3RhdHVzGAYgA
  SgFUgt0cmFkZVN0YXR1cxIkCg1kaWFtb25kQWNvdW50GAcgASgFUg1kaWFtb25kQWNvdW50EhYKBmFtb3VudBgIIAEoCVIGYW1vd
  W50EhwKCWdtdENyZWF0ZRgJIAEoCVIJZ210Q3JlYXRlEhwKCWdtdFVwZGF0ZRgKIAEoCVIJZ210VXBkYXRlEhIKBGV4dDEYCyABK
  AlSBGV4dDESEgoEZXh0MhgMIAEoCVIEZXh0MhISCgRleHQzGA0gASgJUgRleHQzEhIKBGV4dDQYDiABKAlSBGV4dDQSEgoEZXh0N
  RgPIAEoCVIEZXh0NUIuCixjb20ubGF3c29mbmF0dXJlLmFwaWdhdGV3YXkuZG9tYWluLmh0dHAucmVzcGIGcHJvdG8z"""
      ).mkString))
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(proto, Array(
    ))
  }
}