// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package com.proto.test

object TestProto {
  lazy val descriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val proto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(
      com.trueaccord.scalapb.Encoding.fromBase64(scala.collection.Seq(
  """Cgp0ZXN0LnByb3RvIisKB1Rlc3RCdWYSDgoCSUQYASABKAVSAklEEhAKA1VybBgCIAEoCVIDVXJsQhoKCWNvbS5wcm90b0INR
  mlyc3RQcm90b2J1ZmIGcHJvdG8z"""
      ).mkString))
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(proto, Array(
    ))
  }
}