// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package com.lawsofnature.apigateway.domain.http.resp.channellist

object ChannellistProto {
  lazy val descriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val proto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(
      com.trueaccord.scalapb.Encoding.fromBase64(scala.collection.Seq(
  """ChZyZXNwL2NoYW5uZWxsaXN0LnByb3RvIpUBCgdDaGFubmVsEhIKBGNvZGUYASABKAlSBGNvZGUSEgoEbmFtZRgCIAEoCVIEb
  mFtZRISCgRleHQxGAMgASgJUgRleHQxEhIKBGV4dDIYBCABKAlSBGV4dDISEgoEZXh0MxgFIAEoCVIEZXh0MxISCgRleHQ0GAYgA
  SgJUgRleHQ0EhIKBGV4dDUYByABKAlSBGV4dDUipwEKD0NoYW5uZWxMaXN0UmVzcBISCgRjb2RlGAEgASgJUgRjb2RlEhwKBGxpc
  3QYAiADKAsyCC5DaGFubmVsUgRsaXN0EhIKBGV4dDEYAyABKAlSBGV4dDESEgoEZXh0MhgEIAEoCVIEZXh0MhISCgRleHQzGAUgA
  SgJUgRleHQzEhIKBGV4dDQYBiABKAlSBGV4dDQSEgoEZXh0NRgHIAEoCVIEZXh0NUIuCixjb20ubGF3c29mbmF0dXJlLmFwaWdhd
  GV3YXkuZG9tYWluLmh0dHAucmVzcGIGcHJvdG8z"""
      ).mkString))
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(proto, Array(
    ))
  }
}