// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package com.jxjxgo.apigateway.domain.http.resp.resource

object ResourceProto {
  lazy val descriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val proto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(
      com.trueaccord.scalapb.Encoding.fromBase64(scala.collection.Seq(
        """ChNyZXNwL3Jlc291cmNlLnByb3RvIuYBCghSZXNvdXJjZRIYCgd2ZXJzaW9uGAEgASgFUgd2ZXJzaW9uEiIKDHJlc291cmNlV
  HlwZRgCIAEoBVIMcmVzb3VyY2VUeXBlEhIKBGNvZGUYAyABKAlSBGNvZGUSEAoDbGFuGAQgASgJUgNsYW4SEgoEZGVzYxgFIAEoC
  VIEZGVzYxISCgRleHQxGAYgASgJUgRleHQxEhIKBGV4dDIYByABKAlSBGV4dDISEgoEZXh0MxgIIAEoCVIEZXh0MxISCgRleHQ0G
  AkgASgJUgRleHQ0EhIKBGV4dDUYCiABKAlSBGV4dDUiywEKDFJlc291cmNlUmVzcBISCgRjb2RlGAEgASgJUgRjb2RlEiQKDWxhd
  GVzdFZlcnNpb24YAiABKAVSDWxhdGVzdFZlcnNpb24SHQoEbGlzdBgDIAMoCzIJLlJlc291cmNlUgRsaXN0EhIKBGV4dDEYBCABK
  AlSBGV4dDESEgoEZXh0MhgFIAEoCVIEZXh0MhISCgRleHQzGAYgASgJUgRleHQzEhIKBGV4dDQYByABKAlSBGV4dDQSEgoEZXh0N
  RgIIAEoCVIEZXh0NUIuCixjb20ubGF3c29mbmF0dXJlLmFwaWdhdGV3YXkuZG9tYWluLmh0dHAucmVzcGIGcHJvdG8z"""
      ).mkString))
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(proto, Array(
    ))
  }
}