// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package com.lawsofnature.apigateway.domain.http.resp.pricelist

object PricelistProto {
  lazy val descriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val proto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(
      com.trueaccord.scalapb.Encoding.fromBase64(scala.collection.Seq(
  """ChRyZXNwL3ByaWNlbGlzdC5wcm90byK7AQoFUHJpY2USEgoEY29kZRgBIAEoCVIEY29kZRIkCg1kaWFtb25kQW1vdW50GAIgA
  SgFUg1kaWFtb25kQW1vdW50EhQKBXByaWNlGAMgASgJUgVwcmljZRISCgRleHQxGAQgASgJUgRleHQxEhIKBGV4dDIYBSABKAlSB
  GV4dDISEgoEZXh0MxgGIAEoCVIEZXh0MxISCgRleHQ0GAcgASgJUgRleHQ0EhIKBGV4dDUYCCABKAlSBGV4dDUiowEKDVByaWNlT
  GlzdFJlc3ASEgoEY29kZRgBIAEoCVIEY29kZRIaCgRsaXN0GAIgAygLMgYuUHJpY2VSBGxpc3QSEgoEZXh0MRgDIAEoCVIEZXh0M
  RISCgRleHQyGAQgASgJUgRleHQyEhIKBGV4dDMYBSABKAlSBGV4dDMSEgoEZXh0NBgGIAEoCVIEZXh0NBISCgRleHQ1GAcgASgJU
  gRleHQ1Qi4KLGNvbS5sYXdzb2ZuYXR1cmUuYXBpZ2F0ZXdheS5kb21haW4uaHR0cC5yZXNwYgZwcm90bzM="""
      ).mkString))
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(proto, Array(
    ))
  }
}