// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package com.jxjxgo.apigateway.domain.http.req.simple

@SerialVersionUID(0L)
final case class SimpleReq(
                            param0: String = "",
                            param1: String = "",
                            ext1: String = "",
                            ext2: String = "",
                            ext3: String = "",
                            ext4: String = "",
                            ext5: String = ""
                          ) extends com.trueaccord.scalapb.GeneratedMessage with com.trueaccord.scalapb.Message[SimpleReq] with com.trueaccord.lenses.Updatable[SimpleReq] {
  @transient
  private[this] var __serializedSizeCachedValue: Int = 0

  private[this] def __computeSerializedValue(): Int = {
    var __size = 0
    if (param0 != "") {
      __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(1, param0)
    }
    if (param1 != "") {
      __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(2, param1)
    }
    if (ext1 != "") {
      __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(3, ext1)
    }
    if (ext2 != "") {
      __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(4, ext2)
    }
    if (ext3 != "") {
      __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(5, ext3)
    }
    if (ext4 != "") {
      __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(6, ext4)
    }
    if (ext5 != "") {
      __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(7, ext5)
    }
    __size
  }

  final override def serializedSize: Int = {
    var read = __serializedSizeCachedValue
    if (read == 0) {
      read = __computeSerializedValue()
      __serializedSizeCachedValue = read
    }
    read
  }

  def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): Unit = {
    {
      val __v = param0
      if (__v != "") {
        _output__.writeString(1, __v)
      }
    };
    {
      val __v = param1
      if (__v != "") {
        _output__.writeString(2, __v)
      }
    };
    {
      val __v = ext1
      if (__v != "") {
        _output__.writeString(3, __v)
      }
    };
    {
      val __v = ext2
      if (__v != "") {
        _output__.writeString(4, __v)
      }
    };
    {
      val __v = ext3
      if (__v != "") {
        _output__.writeString(5, __v)
      }
    };
    {
      val __v = ext4
      if (__v != "") {
        _output__.writeString(6, __v)
      }
    };
    {
      val __v = ext5
      if (__v != "") {
        _output__.writeString(7, __v)
      }
    };
  }

  def mergeFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): com.jxjxgo.apigateway.domain.http.req.simple.SimpleReq = {
    var __param0 = this.param0
    var __param1 = this.param1
    var __ext1 = this.ext1
    var __ext2 = this.ext2
    var __ext3 = this.ext3
    var __ext4 = this.ext4
    var __ext5 = this.ext5
    var _done__ = false
    while (!_done__) {
      val _tag__ = _input__.readTag()
      _tag__ match {
        case 0 => _done__ = true
        case 10 =>
          __param0 = _input__.readString()
        case 18 =>
          __param1 = _input__.readString()
        case 26 =>
          __ext1 = _input__.readString()
        case 34 =>
          __ext2 = _input__.readString()
        case 42 =>
          __ext3 = _input__.readString()
        case 50 =>
          __ext4 = _input__.readString()
        case 58 =>
          __ext5 = _input__.readString()
        case tag => _input__.skipField(tag)
      }
    }
    com.jxjxgo.apigateway.domain.http.req.simple.SimpleReq(
      param0 = __param0,
      param1 = __param1,
      ext1 = __ext1,
      ext2 = __ext2,
      ext3 = __ext3,
      ext4 = __ext4,
      ext5 = __ext5
    )
  }

  def withParam0(__v: String): SimpleReq = copy(param0 = __v)

  def withParam1(__v: String): SimpleReq = copy(param1 = __v)

  def withExt1(__v: String): SimpleReq = copy(ext1 = __v)

  def withExt2(__v: String): SimpleReq = copy(ext2 = __v)

  def withExt3(__v: String): SimpleReq = copy(ext3 = __v)

  def withExt4(__v: String): SimpleReq = copy(ext4 = __v)

  def withExt5(__v: String): SimpleReq = copy(ext5 = __v)

  def getField(__field: _root_.com.google.protobuf.Descriptors.FieldDescriptor): scala.Any = {
    __field.getNumber match {
      case 1 => {
        val __t = param0
        if (__t != "") __t else null
      }
      case 2 => {
        val __t = param1
        if (__t != "") __t else null
      }
      case 3 => {
        val __t = ext1
        if (__t != "") __t else null
      }
      case 4 => {
        val __t = ext2
        if (__t != "") __t else null
      }
      case 5 => {
        val __t = ext3
        if (__t != "") __t else null
      }
      case 6 => {
        val __t = ext4
        if (__t != "") __t else null
      }
      case 7 => {
        val __t = ext5
        if (__t != "") __t else null
      }
    }
  }

  override def toString: String = _root_.com.trueaccord.scalapb.TextFormat.printToUnicodeString(this)

  def companion = com.jxjxgo.apigateway.domain.http.req.simple.SimpleReq
}

object SimpleReq extends com.trueaccord.scalapb.GeneratedMessageCompanion[com.jxjxgo.apigateway.domain.http.req.simple.SimpleReq] {
  implicit def messageCompanion: com.trueaccord.scalapb.GeneratedMessageCompanion[com.jxjxgo.apigateway.domain.http.req.simple.SimpleReq] = this

  def fromFieldsMap(__fieldsMap: scala.collection.immutable.Map[_root_.com.google.protobuf.Descriptors.FieldDescriptor, scala.Any]): com.jxjxgo.apigateway.domain.http.req.simple.SimpleReq = {
    require(__fieldsMap.keys.forall(_.getContainingType() == descriptor), "FieldDescriptor does not match message type.")
    val __fields = descriptor.getFields
    com.jxjxgo.apigateway.domain.http.req.simple.SimpleReq(
      __fieldsMap.getOrElse(__fields.get(0), "").asInstanceOf[String],
      __fieldsMap.getOrElse(__fields.get(1), "").asInstanceOf[String],
      __fieldsMap.getOrElse(__fields.get(2), "").asInstanceOf[String],
      __fieldsMap.getOrElse(__fields.get(3), "").asInstanceOf[String],
      __fieldsMap.getOrElse(__fields.get(4), "").asInstanceOf[String],
      __fieldsMap.getOrElse(__fields.get(5), "").asInstanceOf[String],
      __fieldsMap.getOrElse(__fields.get(6), "").asInstanceOf[String]
    )
  }

  def descriptor: _root_.com.google.protobuf.Descriptors.Descriptor = SimpleProto.descriptor.getMessageTypes.get(0)

  def messageCompanionForField(__field: _root_.com.google.protobuf.Descriptors.FieldDescriptor): _root_.com.trueaccord.scalapb.GeneratedMessageCompanion[_] = throw new MatchError(__field)

  def enumCompanionForField(__field: _root_.com.google.protobuf.Descriptors.FieldDescriptor): _root_.com.trueaccord.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__field)

  lazy val defaultInstance = com.jxjxgo.apigateway.domain.http.req.simple.SimpleReq(
  )

  implicit class SimpleReqLens[UpperPB](_l: _root_.com.trueaccord.lenses.Lens[UpperPB, com.jxjxgo.apigateway.domain.http.req.simple.SimpleReq]) extends _root_.com.trueaccord.lenses.ObjectLens[UpperPB, com.jxjxgo.apigateway.domain.http.req.simple.SimpleReq](_l) {
    def param0: _root_.com.trueaccord.lenses.Lens[UpperPB, String] = field(_.param0)((c_, f_) => c_.copy(param0 = f_))

    def param1: _root_.com.trueaccord.lenses.Lens[UpperPB, String] = field(_.param1)((c_, f_) => c_.copy(param1 = f_))

    def ext1: _root_.com.trueaccord.lenses.Lens[UpperPB, String] = field(_.ext1)((c_, f_) => c_.copy(ext1 = f_))

    def ext2: _root_.com.trueaccord.lenses.Lens[UpperPB, String] = field(_.ext2)((c_, f_) => c_.copy(ext2 = f_))

    def ext3: _root_.com.trueaccord.lenses.Lens[UpperPB, String] = field(_.ext3)((c_, f_) => c_.copy(ext3 = f_))

    def ext4: _root_.com.trueaccord.lenses.Lens[UpperPB, String] = field(_.ext4)((c_, f_) => c_.copy(ext4 = f_))

    def ext5: _root_.com.trueaccord.lenses.Lens[UpperPB, String] = field(_.ext5)((c_, f_) => c_.copy(ext5 = f_))
  }

  final val PARAM0_FIELD_NUMBER = 1
  final val PARAM1_FIELD_NUMBER = 2
  final val EXT1_FIELD_NUMBER = 3
  final val EXT2_FIELD_NUMBER = 4
  final val EXT3_FIELD_NUMBER = 5
  final val EXT4_FIELD_NUMBER = 6
  final val EXT5_FIELD_NUMBER = 7
}
