// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package com.lawsofnature.apigateway.domain.http.req.login

object LoginProto {
  lazy val descriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val proto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(
      com.trueaccord.scalapb.Encoding.fromBase64(scala.collection.Seq(
  """Cg9yZXEvbG9naW4ucHJvdG8iqgIKCExvZ2luUmVxEhoKCGNsaWVudElkGAEgASgFUghjbGllbnRJZBIYCgd2ZXJzaW9uGAIgA
  SgJUgd2ZXJzaW9uEh4KCmRldmljZVR5cGUYAyABKAVSCmRldmljZVR5cGUSIAoLZmluZ2VyUHJpbnQYBCABKAlSC2ZpbmdlclBya
  W50EhYKBm1vYmlsZRgFIAEoCVIGbW9iaWxlEioKEHZlcmlmaWNhdGlvbkNvZGUYBiABKAlSEHZlcmlmaWNhdGlvbkNvZGUSEgoEZ
  Xh0MRgHIAEoCVIEZXh0MRISCgRleHQyGAggASgJUgRleHQyEhIKBGV4dDMYCSABKAlSBGV4dDMSEgoEZXh0NBgKIAEoCVIEZXh0N
  BISCgRleHQ1GAsgASgJUgRleHQ1Qi0KK2NvbS5sYXdzb2ZuYXR1cmUuYXBpZ2F0ZXdheS5kb21haW4uaHR0cC5yZXFiBnByb3RvM
  w=="""
      ).mkString))
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(proto, Array(
    ))
  }
}