// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package com.jxjxgo.apigateway.domain.http.req.updatenickname

object UpdatenicknameProto {
  lazy val descriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val proto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(
      com.trueaccord.scalapb.Encoding.fromBase64(scala.collection.Seq(
        """ChhyZXEvdXBkYXRlbmlja25hbWUucHJvdG8ikwEKEVVwZGF0ZU5pY2tOYW1lUmVxEhoKCG5pY2tOYW1lGAEgASgJUghuaWNrT
  mFtZRISCgRleHQxGAIgASgJUgRleHQxEhIKBGV4dDIYAyABKAlSBGV4dDISEgoEZXh0MxgEIAEoCVIEZXh0MxISCgRleHQ0GAUgA
  SgJUgRleHQ0EhIKBGV4dDUYBiABKAlSBGV4dDVCLQorY29tLmxhd3NvZm5hdHVyZS5hcGlnYXRld2F5LmRvbWFpbi5odHRwLnJlc
  WIGcHJvdG8z"""
      ).mkString))
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(proto, Array(
    ))
  }
}